include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    require_trailing_commas: true
    use_super_parameters: true